baseURL: "https://parameshwar-a.github.io/"
title: Lifewithlinux
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  homeInfoParams:
    Title: "LifeWithLinux"
    content: >
      Welcome to LifeWithLinux!
      
      - Random but useful guides, tips, tricks for Linux users

      - Happy exploring!

   
menu:
  main:
    - name: Archive
      url: archives
      weight: 5 
    - name: Tags
      url: tags/
      weight: 10
    - name: Search
      url: search/
      weight: 10


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

